//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dijagnoze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dijagnoze()
        {
            this.Terapije = new HashSet<Terapije>();
        }
    
        public int Id { get; set; }
        public int PacijentiId { get; set; }
        public int BolestiId { get; set; }
        public int ZaposleniciId { get; set; }
        public string Napomena { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Bolesti Bolesti { get; set; }
        public virtual Pacijenti Pacijenti { get; set; }
        public virtual Zaposlenici Zaposlenici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terapije> Terapije { get; set; }
    }
}
