//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudžbenice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudžbenice()
        {
            this.NarudžbenicaStavke = new HashSet<NarudžbenicaStavke>();
        }
    
        public int Id { get; set; }
        public System.DateTime Datum { get; set; }
        public int PoslovniPartneriId { get; set; }
        public int ZaposleniciId { get; set; }
        public Nullable<decimal> Iznos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudžbenicaStavke> NarudžbenicaStavke { get; set; }
        public virtual PoslovniPartneri PoslovniPartneri { get; set; }
        public virtual Zaposlenici Zaposlenici { get; set; }
    }
}
