//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudžbenicaStavke
    {
        public int Id { get; set; }
        public int NarudžbeniceId { get; set; }
        public int ProizvodiId { get; set; }
        public int Količina { get; set; }
        public decimal IznosStavke { get; set; }
    
        public virtual Narudžbenice Narudžbenice { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
