//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvodi()
        {
            this.NarudžbenicaStavke = new HashSet<NarudžbenicaStavke>();
            this.Recepti = new HashSet<Recepti>();
            this.StavkeRacuna = new HashSet<StavkeRacuna>();
            this.Terapije = new HashSet<Terapije>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public int TipProizvodaId { get; set; }
        public Nullable<decimal> Cijena { get; set; }
        public int KolicinaSkladiste { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudžbenicaStavke> NarudžbenicaStavke { get; set; }
        public virtual TipProizvoda TipProizvoda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepti> Recepti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkeRacuna> StavkeRacuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terapije> Terapije { get; set; }
    }
}
