//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkeRacuna
    {
        public int Id { get; set; }
        public Nullable<int> RačuniId { get; set; }
        public Nullable<int> ProizvodiId { get; set; }
        public Nullable<int> Količina { get; set; }
    
        public virtual Proizvodi Proizvodi { get; set; }
        public virtual Racuni Racuni { get; set; }
    }
}
