//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terapije
    {
        public int Id { get; set; }
        public int ProizvodiId { get; set; }
        public int DijagnozeId { get; set; }
        public string Preporuka { get; set; }
    
        public virtual Dijagnoze Dijagnoze { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
